/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'timecat' at '3/4/17 12:18 PM' with Gradle 3.0
 *
 * @author timecat, @date 3/4/17 12:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
